In [1]:
#importing Libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Loading the file

In [ ]:
#Loading the Files
# Displaying first five rows
df = pd.read_csv("/kaggle/input/netflix-shows/netflix_titles.csv")
df.head()

# Let have see some insights into the data
- Dataset information
- Dataset types
- Some statistical points (describe functions)

In [ ]:
#info() method
df.info()

In [ ]:
#data types through dtpyes
df.dtypes

In [ ]:
#describe() to see the integers data types
df.describe()

# See any NULL values

In [ ]:
#See if there is any null value inside the data
df.isnull().sum()

In [ ]:
df.isnull().sum().sort_values(ascending=False)

So from the above we have "director" has so many null value than country. \
Now we will see the percentage wise

In [ ]:
round(df.isnull().sum()/df.shape[0]*100,2).sort_values(ascending=False)

So column director has 29.91% data are null and country is just 9.44% of null values.\
So we have two others columns are missing rating and duration but little bit so we drop it.

In [ ]:
df.dropna(subset = ["rating", "duration"], axis=0, inplace=True)

In [ ]:
df.shape

Replace the missing value in country with "Unknown" value

In [ ]:
df["country"].replace(np.NaN, "Unknown", inplace=True)

Now replacing missing values in "cast" column with "No cast"

In [ ]:
df['cast'].replace(np.NaN, "No Cast", inplace = True)

Now replace missing values in "director" columns with "No Director"

In [ ]:
df['director'].replace(np.NaN, "No Director", inplace=True)

In [ ]:
#drop date added colum
df.dropna(subset=["date_added"], axis=0, inplace = True)

In [ ]:
df.isnull().sum()

In [ ]:
# See the columns by calling columns
df.columns

## Filtering for movies and TV Show !
Using the subseting skill to subset the data to filter only movies as we have TV shows and other type shows are there in the dataset.

In [ ]:
df['type'].value_counts()

In [ ]:
df_movies = df[df['type'] == "Movie"]
df_movies.head(2)

In [ ]:
df_tv_show = df[df['type'] == "TV Show"]
df_tv_show.head(2)

In [ ]:
go.Figure(data=[go.Pie(labels=df.type.value_counts(normalize=True).index, 
                       values=df.type.value_counts(normalize=True).values, 
                       hole=.5, title="Movies vs TV Shows")])

As shown clearly that content on Netflix 69.7% are **Movies** and rest 30.3% are **TV Show**.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
fig = plt.figure(figsize=(8,6))
sns.countplot(x="type", data=df)
plt.show()

In [ ]:
#Selecting part of the columns from the dataset
df_movies_sub_cols = df_movies[['title','director','country','release_year','duration']]
df_movies_sub_cols.head(4)

In [ ]:
df['duration'].value_counts()[:5]

# Top Five Netflix Shows

In [ ]:
top_five_most_show = df['duration'].value_counts()[:5]
fig = plt.figure(figsize=(8,6))
plt.xticks(rotation=45)
sns.barplot( x = top_five_most_show.index, y = top_five_most_show, orient='v');
plt.show()

# Top Ten Countries watching Netflix

In [ ]:
#Top ten Countries Wataching Netflix
top_ten_countries = df['country'].value_counts()[:10]
top_ten_countries

In [ ]:
sns.set_style("darkgrid")
fig = plt.figure(figsize=(12,8))
plt.xticks(rotation=70)
sns.barplot(x= top_ten_countries.index, y=top_ten_countries, orient='v')

plt.show()

As above shown that the top countries so **United State** is leading the market than **India** and **United Kingdom**

# Top ten Directors

In [ ]:
#top ten directors
top_ten_directors = df['director'].value_counts()[:10]
top_ten_directors

In [ ]:
sns.set_style("darkgrid")
fig = plt.figure(figsize=(12,8))
plt.xticks(rotation=70)
sns.barplot(x= top_ten_directors.index, y=top_ten_directors, orient='v')
plt.show()

Top ten directors of the Movies and TV Shows. **Rajiv Chilaka** is on the top.

# Top Ten Actors

In [ ]:
cast_shows = df[df.cast != "No Cast"].set_index("title").cast.str.split(',', expand=True).stack().reset_index(level=1, drop=True)
plt.figure(figsize=(10, 8))
plt.title("Top 10 Actors Movives based on the no of titles")
sns.countplot(y = cast_shows, order=cast_shows.value_counts().index[:10], palette="pastel")
plt.show()

**Anupam Kher** is on the top of the list.

# Checking the rating of different movies and shows

In [ ]:
df["rating"].value_counts()

In [ ]:
df['duration'].value_counts()

In [ ]:
# df['duration'] = df['duration'].apply(lambda x: x.strip(' min'))
# df.head()
plt.figure(figsize=(12,8))
sns.barplot(x=df.rating.value_counts(), y=df.rating.value_counts().index, data=df, orient='h')
plt.show()

The highest count **TV-MA** is the rating that shows a program is intended for adults. **MA** stand for **"Mature Audience"**. Children age 17 and younger should not view these programs. \
Second largest is the **'TV-14'**. A **TV-14** program is meant for children over 14 years of age.

In [ ]:
df.columns

# Top Movies or TV shows

In [ ]:
plt.figure(figsize=(12,8))
ax = sns.countplot(y="listed_in",data=df, order=df.listed_in.value_counts().index[0:15])

It is cleared that **"Drama,International Movies"** and **"Documentaries"** are leading in netflix.

# Year wise content

In [ ]:
plt.figure(figsize=(12, 8))
ax = sns.countplot(y= "release_year",data=df, order=df.release_year.value_counts().index[0:10])
plt.show();

During **2018** the content on Netflix was much more watched.

# Some conversion from categorical into numerical
column duration has mint like 90 min so we remove string "min"

In [ ]:
df.duration = df.duration.apply(lambda x: x.replace("min", "")if "min" in x else x)
df.head()

In [ ]:
df.duration = df.duration.apply(lambda x: x.replace("Season", " ")if "Season" in x else x)
df.head()

In [ ]:
df.loc[:, ["duration"]]==df.loc[:, ["duration"]].apply(lambda x: x.astype('int64', errors='ignore'))
df.describe()

In [ ]:
df.head()

### Good Luck! Thank for visiting here.